gui:
  sidePanelWidth: 0.2
git:
  paging:
    colorArg: always
    pager: delta --paging=never -s --features catppuccin-frappe
keybinding:
  universal:
    scrollUpMain: <C-u>
    scrollDownMain: <C-d>
